### ISSUE TITLE
Gregorian to Jalali

### ISSUE THREAD

**Issue by dlbaran** [novid/jalaali-php#1]
I need to display the date stored in the Gregorian database in Jalali. How can I do this using your library?

**Comment by novid** [comment]
Dear Friend,

This is an issue queue for reporting bugs in the library not to ask how to solve problems! Since your'e new to PHP, just look at the **Install & API** section of _README.md_ file. It's exactly what you asked for ;)
You can also have a look at [PHP Manual](https://php.net/manual/en/language.oop5.static.php) for this matter.
